"""empty message

Revision ID: 613126f59600
Revises: e0dde8e0a188
Create Date: 2018-10-10 11:12:11.630967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '613126f59600'
down_revision = 'e0dde8e0a188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rel_table',
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['clas.id'], ),
    sa.ForeignKeyConstraint(['sid'], ['stus.id'], )
    )
    op.add_column('follow', sa.Column('followed_id', sa.Integer(), nullable=False))
    op.add_column('follow', sa.Column('follower_id', sa.Integer(), nullable=False))
    op.drop_constraint('follow_ibfk_1', 'follow', type_='foreignkey')
    op.drop_constraint('follow_ibfk_2', 'follow', type_='foreignkey')
    op.create_foreign_key(None, 'follow', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'follow', 'users', ['followed_id'], ['id'])
    op.drop_column('follow', 'fan_id')
    op.drop_column('follow', 'dav_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow', sa.Column('dav_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('follow', sa.Column('fan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.drop_constraint(None, 'follow', type_='foreignkey')
    op.create_foreign_key('follow_ibfk_2', 'follow', 'users', ['fan_id'], ['id'])
    op.create_foreign_key('follow_ibfk_1', 'follow', 'users', ['dav_id'], ['id'])
    op.drop_column('follow', 'follower_id')
    op.drop_column('follow', 'followed_id')
    op.drop_table('rel_table')
    # ### end Alembic commands ###
