"""empty message

Revision ID: 9f7256bea6e2
Revises: 88bb5ed6efc7
Create Date: 2018-10-11 10:04:52.270771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7256bea6e2'
down_revision = '88bb5ed6efc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###
