"""empty message

Revision ID: d5fc165bbccd
Revises: cc1c59eaae30
Create Date: 2018-10-08 02:02:44.480508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fc165bbccd'
down_revision = 'cc1c59eaae30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('access_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('register_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register_time')
    op.drop_column('users', 'location')
    op.drop_column('users', 'access_time')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
